name: React CI/CD Pipeline

on:
  push:
    branches: [master]   # or [main] if your repo uses main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watchAll=false

    - name: Build app
      run: npm run build

    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://my-ci-cd-react-bucket --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1   # replace with your region
